adding the created_at check to reduce the loading time
meddle0x53/blogit pull request #7
Opened 2020-03-13 00:08 UTC by 9to1url

2020-03-13 00:09 UTC, 9to1url commented
I refactored to fit the PR. please review and accept.

2020-03-13 06:03 UTC, meddle0x53 requested changes
Your idea to not call the provider if we already have the data is right.
I have a few requests, mainly code-style related.

Also you forgot to bump the `mix.exs` version (at least I don't see the bump in the PR)

2020-03-13 06:03 UTC, meddle0x53 commented on lib/blogit/models/post/meta.ex
> +        IO.inspect "get from REPO using git log:" <> file_path
Use the `Logger` and not `IO` for logging.

2020-03-13 06:03 UTC, meddle0x53 commented on lib/blogit/models/post/meta.ex
> +      if created_at == nil do
Only when the `created_at` is `nil`?
Shouldn't it be `if is_nil(created_at) || is_nil(updated_at) || is_nil(author)  do`?
Basically you have to set all three of them to not ask the provider.

Also use `is_nil` to check for `nil`s.

2020-03-13 06:03 UTC, meddle0x53 commented on lib/blogit/models/post/meta.ex
> +    {created_at2, updated_at2, author2} =
I prefer naming them in a way we know where they came from:
`created_at_from_provider` for example and similar naming for the others.

2020-03-13 06:03 UTC, meddle0x53 commented on lib/blogit/models/post/meta.ex
> +        created_at3 = file_info[:created_at] || "2020-01-26T01:01:01"
Use `DateTime.utc_now() |> DateTime.to_iso8601()` for the default. Don't hardcode dates.
Also don't name them here, just return:
```
{
  file_info[:created_at] || DateTime.utc_now() |> DateTime.to_iso8601(),
  updated_at || file_info[:updated_at] || DateTime.utc_now() |> DateTime.to_iso8601(),
  author || file_info[:author] || "Anonymous"
}
```

2020-03-13 06:03 UTC, meddle0x53 commented on lib/blogit/models/post/meta.ex
> +        {nil,nil,nil}
Add spaces between `nil,` and the next `nil`.
We should introduce the formatter to this project.

2020-03-13 18:01 UTC, 9to1url commented
fixed all the issues you mentioned in code review. thanks.

2020-03-16 09:38 UTC, meddle0x53 approved these changes
Very cool!
Thanks a lot!

2020-03-16 09:38 UTC, merged